# Generated by Django 3.2.13 on 2023-04-26 07:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpdRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipd_no', models.CharField(max_length=20)),
                ('patient_name', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('doctor', models.CharField(max_length=20)),
                ('bed_group', models.CharField(max_length=30)),
                ('bed_no', models.CharField(max_length=20)),
                ('symptoms', models.CharField(max_length=20)),
                ('fees', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=20)),
                ('comapny_name', models.CharField(max_length=20)),
                ('medicine_category', models.CharField(max_length=20)),
                ('medicine_group', models.CharField(max_length=20)),
                ('pack', models.IntegerField()),
                ('unit_pack', models.IntegerField()),
                ('rupees', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OpdRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=30)),
                ('blood_group', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
                ('asigned_doctor', models.CharField(max_length=45)),
                ('fees', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TestRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('doctor', models.CharField(max_length=20)),
                ('testcase', multiselectfield.db.fields.MultiSelectField(choices=[('fever', 'fever'), ('cough', 'cough'), ('diabetes', 'diabetes'), ('hemoglobin', 'hemoglobin'), ('vitamin', 'vitamin'), ('urin', 'urin'), ('Radiology X-ray', 'Radiology X-ray'), ('MRI', 'MRI'), ('thyroid', 'thyroid')], max_length=72, null=True)),
                ('fees', models.FloatField()),
            ],
        ),
    ]
